name: Check for Secrets

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  git-secrets-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run git-secrets setup script
      run: |
        chmod +x setup-git-secrets.sh
        ./setup-git-secrets.sh
