name: Check Secrets

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  git-secrets-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install git-secrets
      run: |
        sudo apt-get update
        sudo apt-get install -y git-secrets

    - name: Run git-secrets setup script
      run: |
        chmod +x setup-git-secrets.sh
        ./setup-git-secrets.sh

    - name: Scan repository for secrets
      run: git secrets --scan --recursive
