name: Cpplint Check

on:
  pull_request:
    branches:
      - main

jobs:
  cpplint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Cpplint
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install cpplint

    - name: Run Cpplint
      run: find . -name '*.c' -o -name '*.h' | xargs cpplint
