name: Pre-commit checks

on:
  push:
    branches:
      - main

jobs:
  precommit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format cppcheck

    - name: Run cppcheck
      run: |
        cppcheck --enable=warning --force --error-exitcode=1 --language=c --output-file=cppcheck-results.txt $(find . -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp')
        cat cppcheck-results.txt

    - name: Run clang-format
      run: |
        find . -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp' | xargs clang-format -i
        git diff --exit-code
