name: Static Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Cppcheck and Cpplint
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck python3-pip
        pip3 install cpplint

    - name: Run Cppcheck
      run: cppcheck --enable=all --error-exitcode=1 .

    - name: Run Cpplint
      run: find . -name '*.c' -o -name '*.h' | xargs cpplint --filter=-legal/copyright
